services:
  sonarview:
    image: nicknothom/sonarview:latest
    container_name: sonarview
    network_mode: host
    restart: unless-stopped

    privileged: true 

    volumes:
      - /usr/SonarView:/userdata

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

    group_add:
      - dialout
      - "20"

    environment:
      - ENABLE_OS3D=false