# ==================== Base: JetPack 6.2.1 (L4T r36.4) ====================
FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

# -------------------- ROS 2 Humble + Base Deps --------------------
RUN apt-get update && apt-get install -y curl gnupg2 lsb-release \
 && curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg \
 && echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
    > /etc/apt/sources.list.d/ros2.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
      ros-humble-ros-base \
      python3-rosdep \
      python3-vcstool \
      python3-colcon-common-extensions \
      build-essential \
 && rosdep init || true \
 && rosdep update \
 && rm -rf /var/lib/apt/lists/*

 # -------------------- Additional Apt Packages --------------------
RUN apt-get update && apt-get install -y software-properties-common \
 && apt-add-repository -y universe && apt-get update \
 && apt-get install -y --no-install-recommends \
      python3-pip python3-serial python3-venv \
      sudo xauth htop udev zip unzip \
      libboost-all-dev libasio-dev \
      git \
      libsm6 libxext6 libxrender1 libfontconfig1 libgl1 libpcap-dev libopencv-dev libyaml-cpp-dev libeigen3-dev libopenblas-dev libopenblas-base \
      ros-humble-diagnostic-updater \
      ros-humble-nmea-msgs \
      ros-humble-rtcm-msgs \
      ros-humble-rosbridge-server \
      ros-humble-rosx-introspection \
      ros-humble-foxglove-bridge \
      ros-humble-image-transport \
      ros-humble-image-transport-plugins \
      ros-humble-compressed-image-transport \
      ros-humble-xacro \
      ros-humble-vision-opencv \
      ros-humble-geographic-msgs \
      ros-humble-robot-localization \
      ros-humble-backward-ros \
      ros-humble-tf2-ros \
      ros-humble-tf2-geometry-msgs \
      ros-humble-message-filters \
      ros-humble-camera-info-manager \
      ros-humble-laser-filters \
      ros-humble-v4l2-camera \
 && ln -sf /usr/bin/python3 /usr/bin/python \
 && chmod -R a+rX /usr/local/lib/python3.10/dist-packages /usr/lib/python3/dist-packages \
 && rm -rf /var/lib/apt/lists/*

# -------------------- Create non-root user --------------------
ARG USERNAME=mavlab
ENV USERNAME=${USERNAME}
RUN useradd -m "${USERNAME}" \
 && echo "${USERNAME}:${USERNAME}" | chpasswd \
 && usermod --shell /bin/bash "${USERNAME}" \
 && usermod -aG sudo,dialout,video,plugdev "${USERNAME}" \
 && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
 && chmod 0440 /etc/sudoers.d/${USERNAME}

# -------------------- Python venv + pip packages --------------------
USER ${USERNAME}
WORKDIR /home/${USERNAME}

RUN python3 -m venv --system-site-packages /home/${USERNAME}/.venv

ENV VIRTUAL_ENV=/home/${USERNAME}/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY --chown=${USERNAME}:${USERNAME} requirements.txt /home/${USERNAME}/requirements.txt

# Upgrade pip tools
RUN python3 -m pip install --upgrade pip setuptools wheel

# Install remaining Python dependencies
RUN pip install --no-cache-dir --no-deps -r /home/${USERNAME}/requirements.txt

RUN echo 'source $VIRTUAL_ENV/bin/activate' >> ~/.bashrc

# -------------------- Arduino CLI setup --------------------
RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
ENV PATH="/home/${USERNAME}/bin:${PATH}"
ENV ARDUINO_DATA="/home/${USERNAME}/.arduino15"

RUN arduino-cli config init \
 && arduino-cli config set directories.data "${ARDUINO_DATA}" \
 && arduino-cli core update-index \
 && arduino-cli core install arduino:mbed_portenta \
 && arduino-cli lib install Servo \
 && arduino-cli cache clean

# -------------------- MicroROS and FlySkyIBus arduino Library setup --------------------

COPY --chown=${USERNAME}:${USERNAME} micro_ros_arduino.zip /tmp/micro_ros_arduino.zip
RUN printf "board_manager:\n  additional_urls: []\n\nlibrary:\n  enable_unsafe_install: true\n" > /home/${USERNAME}/.arduino15/arduino-cli.yaml \
 && arduino-cli --config-file /home/${USERNAME}/.arduino15/arduino-cli.yaml lib install --zip-path /tmp/micro_ros_arduino.zip \
 && rm /tmp/micro_ros_arduino.zip

COPY --chown=${USERNAME}:${USERNAME} FlySkyIBus_modified_portenta.zip /tmp/FlySkyIBus.zip
RUN arduino-cli --config-file /home/${USERNAME}/.arduino15/arduino-cli.yaml lib install --zip-path /tmp/FlySkyIBus.zip \
 && rm /tmp/FlySkyIBus.zip

COPY --chown=${USERNAME}:${USERNAME} BlueRobotics_MS5837.zip /tmp/BlueRobotics_MS5837.zip
RUN arduino-cli --config-file /home/${USERNAME}/.arduino15/arduino-cli.yaml lib install --zip-path /tmp/BlueRobotics_MS5837.zip \
 && rm /tmp/BlueRobotics_MS5837.zip

# -------------------- Sensor ROS Packages to home/mavlab/ros2_ws --------------------

COPY --chown=${USERNAME}:${USERNAME} packages /home/${USERNAME}/ros2_ws/src

# Remove ZED wrapper for zedless image
RUN rm -rf /home/${USERNAME}/ros2_ws/src/zed-ros2-wrapper

WORKDIR /home/${USERNAME}/ros2_ws

USER root
WORKDIR /home/mavlab/ros2_ws
RUN apt-get update && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y
USER ${USERNAME}

# -------------------- Install ping-python/brping --------------------
USER root
WORKDIR /home/${USERNAME}/ros2_ws/src/ping_sonar_ros/ping_sonar_ros/ping-python
RUN /usr/bin/python3 setup.py install
USER ${USERNAME}

# -------------------- Build the sensor ROS Packages once and available directly inside container --------------------
USER root
WORKDIR /home/${USERNAME}/ros2_ws
RUN bash -c "source /opt/ros/humble/setup.bash && \
             colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release --parallel-workers $(nproc)"

# -------------------- ROS 2 bashrc + aliases --------------------
RUN echo 'source /opt/ros/humble/setup.bash' >> /home/${USERNAME}/.bashrc \
 && echo 'if [ -f /home/mavlab/ros2_ws/install/setup.bash ]; then source /home/mavlab/ros2_ws/install/setup.bash; fi' >> /home/${USERNAME}/.bashrc \
 && echo 'if [ -f /workspaces/mavlab/code_ws/install/setup.bash ]; then source /workspaces/mavlab/code_ws/install/setup.bash; fi' >> /home/${USERNAME}/.bashrc \
 && echo "alias sros2='source /opt/ros/humble/setup.bash && source /home/mavlab/ros2_ws/install/setup.bash'" >> /home/${USERNAME}/.bashrc \
 && echo "alias scode='source /opt/ros/humble/setup.bash && source /workspaces/mavlab/code_ws/install/setup.bash'" >> /home/${USERNAME}/.bashrc \
 && echo "alias colb='pushd /workspaces/mavlab/code_ws >/dev/null && sudo rm -rf build log install && colcon build --symlink-install --cmake-args=-DCMAKE_BUILD_TYPE=Release --parallel-workers \$(nproc) && sros2 && popd >/dev/null'" >> /home/${USERNAME}/.bashrc \
 && echo "alias topics='ros2 topic list'" >> /home/${USERNAME}/.bashrc \
 && echo "alias nodes='ros2 node list'" >> /home/${USERNAME}/.bashrc

RUN echo "alias sbg='sros2 && ros2 launch sbg_driver sbg_device_launch.py'" >> /home/${USERNAME}/.bashrc \
 && echo "alias gnc='sros2 && ros2 run gnc gnc'" >> /home/${USERNAME}/.bashrc \
 && echo "alias mavsim='sros2 && ros2 run mav_simulator simulate'" >> /home/${USERNAME}/.bashrc \
 && echo "alias dvl='sros2 && ros2 launch dvl_a50 dvl_a50.launch.py ip_address:='192.168.194.95''" >> /home/${USERNAME}/.bashrc \
 && echo "alias ping360='sros2 && ros2 run ping360_sonar ping360.py --ros-args -p device:=/dev/ping360'" >> /home/${USERNAME}/.bashrc \
 && echo "alias ping2='sros2 && ros2 run ping_sonar_ros ping1d_node --ros-args -p port:=/dev/ping2'" >> /home/${USERNAME}/.bashrc \
 && echo "alias frontcam='sros2 && ros2 run v4l2_camera v4l2_camera_node --ros-args -p video_device:=/dev/frontcam'" >> /home/${USERNAME}/.bashrc \
 && echo "alias bottomcam='sros2 && ros2 run v4l2_camera v4l2_camera_node --ros-args -p video_device:=/dev/bottomcam'" >> /home/${USERNAME}/.bashrc

# -------------------- Expose Ports --------------------
EXPOSE 9000 9001 9002 9003
